apiVersion: v1
kind: Service
metadata:
  name: redis-cache
spec:
  # to be changed to ClusterIP ( only in cluster visibility )
  type: LoadBalancer
  selector:
    app: redis-cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      