apiVersion: v1
kind: ConfigMap
metadata:
  name: web-crawler-config
  namespace: crawler
data:
  redis-cache-host: "redis-cache"
  redis-cache-port: "6379"
  redis-cache-pass: "really_long_password_01"